# .github/workflows/main.yml
name: Build and deploy

### When to run
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
###

permissions:
  contents: write

jobs:
  call-deploy:
    uses: HerodotusDev/cicd/.github/workflows/build-and-deploy.yaml@main


