# .github/workflows/main.yml
name: Build and deploy

### When to run
on:
  workflow_dispatch:
  push:
    branches:
      - main
###

permissions:
  contents: write

jobs:
  call-deploy:
    uses: HerodotusDev/cicd/.github/workflows/build-and-deploy.yaml@arc
    with:
      k8s_env: stage

