name: "Extract Version"
description: "Extracts a version value from a specified JSON or TOML file."

inputs:
  file:
    description: "The file containing the version."
    required: true
  key:
    description: "Optional dot-delimited path to the desired version entry."
    required: false

outputs:
  version:
    description: "The extracted version."
    value: ${{ steps.extract.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Extract Version
      id: extract
      shell: bash
      env:
        VERSION_FILE: ${{ inputs.file }}
        VERSION_KEY: ${{ inputs.key }}
      run: |
        set -euo pipefail
        script_path="${GITHUB_ACTION_PATH}/extract_version.sh"
        if [ ! -f "$VERSION_FILE" ]; then
          echo "File not found: $VERSION_FILE"
          exit 1
        fi

        args=("--file" "$VERSION_FILE")
        if [ -n "${VERSION_KEY:-}" ]; then
          args+=("--key" "$VERSION_KEY")
        fi

        version=$("$script_path" "${args[@]}")
        echo "version=$version" >> "$GITHUB_OUTPUT"
        echo "Extracted version: $version"
