name: "Extract Version"
description: "Extracts the version from a specified file using yq."

inputs:
  file:
    description: "The file containing the version."
    required: true
  version_key:
    description: 'The key under which the version is stored (optional, defaults to ".version").'
    required: false
    default: ".version"
  prefix_with_v:
    description: 'Whether to prefix the version with "v" (true or false).'
    required: false
    default: "false"

outputs:
  version:
    description: "The extracted version."
    value: ${{ steps.extract_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install yq if not present
      shell: bash
      run: |
        if ! command -v yq &> /dev/null; then
          echo "yq could not be found, installing yq..."
          wget https://github.com/mikefarah/yq/releases/download/v4.44.5/yq_linux_amd64 -O yq
          chmod +x yq
          sudo mv yq /usr/local/bin/yq
        else
          echo "yq is already installed."
        fi

    - name: Extract Version
      id: extract_version
      shell: bash
      run: |
        FILE="${{ inputs.file }}"
        VERSION_KEY="${{ inputs.version_key }}"
        PREFIX_WITH_V="${{ inputs.prefix_with_v }}"

        if [ ! -f "$FILE" ]; then
          echo "File not found: $FILE"
          exit 1
        fi

        KEY=${VERSION_KEY:-'.version'}

        # Extract version using yq with raw output
        VERSION=$(yq e -r "${KEY}" "$FILE")

        if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
          echo "Version not found in $FILE using key '${KEY}'."
          exit 1
        fi

        if [ "$PREFIX_WITH_V" = "true" ]; then
          VERSION="v${VERSION}"
        fi

        echo "Extracted version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
