### File containing input variables to be parsed by following github workflows.
### Some keys are set by default in cicd repo, specifying them in this file will overwrite end values.
### Inputs file is 'branch sensitive' - eg. if running a workflow based on branch x - inputs file from branch x will be used. (opposite to workflows)

namespace: example                                # namespace to be deploy  
app_names:                                       # list of app names to deploy, can be single or multiple
  - example
  - example2
dockerhub_project: dataprocessor                  # name of the dockerhub project the image will be pushed to / pulled from
#deployment_file: ./k8s/deployment.yaml           # path to the k8s deployment manifest  // has a default value
#ingress_file: ./k8s/ingress.yaml                 # path to the k8s ingress manifest  // has a default value
#rollout_timeout: 300                             # time which github will wait until deployment rollsout  // has a default value
#pull_etcd_config: true                           # bool - if true, will pull config from etcd
#etcd_key: .env.stage                # path to file to be pulled from etcd