name: "Fetch ETCD Config from K8s"
description: "Fetch configuration from an ETCD instance running inside a Kubernetes cluster"
inputs:
  kube_config:
    description: "Base64 encoded Kubernetes config"
    required: true
  etcd_namespace:
    description: "Namespace where ETCD is running"
    required: true
  etcd_label:
    description: "Label selector for the ETCD pod"
    required: true
  etcd_key:
    description: "Key to fetch from ETCD"
    required: true
  etcd_user:
    description: "ETCD username"
    required: true
  etcd_password:
    description: "ETCD password"
    required: true
outputs:
  value:
    description: "Value retrieved from ETCD"
    value: ${{ steps.fetch.outputs.value }}

runs:
  using: "composite"
  steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      shell: bash
      run: |
        echo "${{ inputs.kube_config }}" | base64 --decode > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Fetch ETCD Config
      id: fetch
      shell: bash
      run: |
        POD_NAME=$(kubectl get pods -n ${{ inputs.etcd_namespace }} -l ${{ inputs.etcd_label }} -o jsonpath='{.items[0].metadata.name}')
        OUTPUT=$(kubectl exec -n ${{ inputs.etcd_namespace }} $POD_NAME -- etcdctl --user="${{ inputs.etcd_user }}:${{ inputs.etcd_password }}" get "${{ inputs.etcd_key }}" --print-value-only)
        
        echo "value=$OUTPUT" >> $GITHUB_OUTPUT