apiVersion: v1
kind: Pod
metadata:
  name: github-actions-runner
  namespace: default  # Change this to your target namespace
spec:
  serviceAccountName: github-actions-deployer
  containers:
  - name: runner
    image: myoung34/github-runner:latest  # This image is specifically designed for running GitHub Actions in containers
    env:
    - name: RUNNER_NAME
      value: "k8s-runner"
    - name: RUNNER_WORKDIR
      value: "/tmp/runner"
    - name: RUNNER_ORG
      value: "your-org"  # Change this to your GitHub organization
    - name: RUNNER_REPO
      value: "your-repo"  # Change this to your repository name
    - name: RUNNER_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-runner-secret
          key: token
    - name: DOCKER_HOST
      value: "unix:///var/run/docker.sock"
    volumeMounts:
    - name: workdir
      mountPath: /tmp/runner
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: workdir
    emptyDir: {}
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
      type: Socket 