name: "Load YAML Inputs as Environment Variables"
description: "Parses a YAML file and sets all key-value pairs as environment variables."


inputs:
  inputs_file:
    description: "Path to the YAML file containing inputs"
    required: true
    default: "workflow-inputs.yaml"

outputs:
  env_vars:
    description: "Serialized key-value pairs from the YAML file"
    value: ${{ steps.export-envs.outputs.env_vars }}

runs:
  using: "composite"
  steps:
    - name: Install yq (YAML parser)
      run: |
        sudo apt update && sudo apt install -y jq wget
        wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
        chmod +x /usr/local/bin/yq
      shell: bash

    - name: Load Inputs Dynamically from YAML
      id: export-envs
      run: |
        if [ ! -f "${{ inputs.inputs_file }}" ]; then
          echo "❌ Error: File ${{ inputs.inputs_file }} not found!"
          exit 1
        fi

        echo "✅ Parsing YAML and exporting variables..."
        
        # Convert YAML to JSON and store in output
        JSON_OUTPUT=$(yq -o=json '.' "${{ inputs.inputs_file }}" | jq -c)

        # Store JSON output for use in following jobs
        echo "env_vars=$JSON_OUTPUT" >> "$GITHUB_OUTPUT"

        echo "✅ Loaded input variables:"
        echo "$JSON_OUTPUT"
      shell: bash

