name: "Load Inputs as Environment Variables"
description: "Reads a YAML file and sets all key-value pairs as environment variables directly."

inputs:
  inputs_file:
    description: "Path to the YAML file containing inputs"
    required: true
    default: "workflow-inputs.yaml"

runs:
  using: "composite"
  steps:
    - name: Load Inputs and Set Environment Variables
      run: |
        if [ ! -f "${{ inputs.inputs_file }}" ]; then
          echo "❌ Error: File ${{ inputs.inputs_file }} not found!"
          exit 1
        fi

        echo "✅ Reading input variables..."
        
        # Read the file line by line and set environment variables
        while IFS= read -r line; do
          # Skip empty lines and full-line comments
          if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            continue
          fi
          
          # Remove inline comments and trim
          line="${line%%#*}"
          line="${line%"${line##*[![:space:]]}"}"
          
          # Extract key and value
          if [[ "$line" =~ ^([^:]+):[[:space:]]*(.+)$ ]]; then
            key="${BASH_REMATCH[1]}"
            value="${BASH_REMATCH[2]}"
            
            # Remove quotes if present and trim
            value="${value%\"}"
            value="${value#\"}"
            value="${value%"${value##*[![:space:]]}"}"
            
            # Set the environment variable
            echo "$key=$value" >> "$GITHUB_ENV"
            echo "Set $key=$value"
          fi
        done < "${{ inputs.inputs_file }}"
        
        echo "✅ All variables loaded successfully"
      shell: bash

