name: "Load Inputs as Environment Variables"
description: "Reads a YAML file and sets all key-value pairs as environment variables directly."

inputs:
  inputs_file:
    description: "Path to the YAML file containing inputs"
    required: true
    default: "workflow-inputs.yaml"

outputs:
  app_names:
    description: "The app_names value from the inputs file"
    value: ${{ steps.load-inputs.outputs.app_names }}

runs:
  using: "composite"
  steps:
    - name: Load Inputs and Set Environment Variables
      id: load-inputs
      run: |
        if [ ! -f "${{ inputs.inputs_file }}" ]; then
          echo "❌ Error: File ${{ inputs.inputs_file }} not found!"
          exit 1
        fi

        echo "✅ Reading input variables..."
        
        # Read the file line by line and set environment variables
        while IFS= read -r line || [ -n "$line" ]; do  # Added -n "$line" to catch the last line
          # Skip empty lines and full-line comments
          if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            continue
          fi
          
          # Remove inline comments and trim
          original_line="$line"
          line="${line%%#*}"
          line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          
          # Extract key and value using improved pattern matching
          if [[ "$line" =~ ^([^:]+)[[:space:]]*:[[:space:]]*(.+)$ ]]; then
            key="$(echo "${BASH_REMATCH[1]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            value="$(echo "${BASH_REMATCH[2]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            
            # Remove quotes if present
            value="${value%\"}"
            value="${value#\"}"
            
            # Set the environment variable
            echo "$key=$value" >> "$GITHUB_ENV"
            echo "Set $key=$value"

            # Set app_names as output if it's the app_names key
            if [ "$key" = "app_names" ]; then
              echo "Debug: Processing app_names value: $value"
              
              # Split the comma-separated string into an array
              IFS=',' read -ra APPS <<< "$value"
              
              # Create JSON array with proper formatting
              JSON_ARRAY='['
              for ((i=0; i<${#APPS[@]}; i++)); do
                if [ $i -gt 0 ]; then
                  JSON_ARRAY="$JSON_ARRAY,"
                fi
                JSON_ARRAY="$JSON_ARRAY\"${APPS[$i]}\""
              done
              JSON_ARRAY="$JSON_ARRAY]"
              
              echo "Debug: Generated JSON array: $JSON_ARRAY"
              echo "app_names=$JSON_ARRAY" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "⚠️ Warning: Could not parse line: '$original_line'"
          fi
        done < "${{ inputs.inputs_file }}"
        
        echo "✅ All variables loaded successfully"
      shell: bash

