name: "Load Inputs as Environment Variables"
description: "Reads a YAML file and sets all key-value pairs as environment variables directly."

inputs:
  inputs_file:
    description: "Path to the YAML file containing inputs"
    required: true
    default: "workflow-inputs.yaml"

runs:
  using: "composite"
  steps:
    - name: Load Inputs and Set Environment Variables
      run: |
        if [ ! -f "${{ inputs.inputs_file }}" ]; then
          echo "❌ Error: File ${{ inputs.inputs_file }} not found!"
          exit 1
        fi

        echo "✅ Reading input variables..."
        echo "📄 Processing file: ${{ inputs.inputs_file }}"
        
        # Read the file line by line and set environment variables
        while IFS= read -r line || [ -n "$line" ]; do  # Added -n "$line" to catch the last line
          # Debug: Print raw line
          echo "📝 Processing line: '$line'"
          
          # Skip empty lines and full-line comments
          if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
            echo "⏭️ Skipping comment or empty line"
            continue
          fi
          
          # Remove inline comments and trim
          original_line="$line"
          line="${line%%#*}"
          line="$(echo "$line" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
          
          # Extract key and value using improved pattern matching
          if [[ "$line" =~ ^([^:]+)[[:space:]]*:[[:space:]]*(.+)$ ]]; then
            key="$(echo "${BASH_REMATCH[1]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            value="$(echo "${BASH_REMATCH[2]}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"
            
            # Remove quotes if present
            value="${value%\"}"
            value="${value#\"}"
            
            # Set the environment variable
            echo "$key=$value" >> "$GITHUB_ENV"
            echo "✅ Set $key=$value"
          else
            echo "⚠️ Warning: Could not parse line: '$original_line'"
          fi
        done < "${{ inputs.inputs_file }}"
        
        echo "✅ All variables loaded successfully"
        echo "📋 Final environment variables:"
        cat "$GITHUB_ENV"
      shell: bash

