
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ app_name }}-tls
spec:
  secretName: {{ app_name }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ app_name }}.api.herodotus.cloud
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ app_name }}-ingress
  annotations:
    spec.ingressClassName: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - {{ app_name }}.api.herodotus.cloud
      secretName: {{ app_name }}-tls
  rules:
    - host: {{ app_name }}.api.herodotus.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ app_name }}-service
                port:
                  number: {{ service_port }}
