name: 'Fetch ETCD Config and Create Secret'
description: 'Fetch configuration from an external ETCD instance and create a Kubernetes Secret'

inputs:
  etcd_host:
    description: 'ETCD endpoint'
    required: true
  etcd_user:
    description: 'ETCD username'
    required: true
  etcd_password:
    description: 'ETCD password'
    required: true
  etcd_key:
    description: 'ETCD key to fetch'
    required: true
  namespace:
    description: 'Kubernetes namespace for the Secret'
    required: false
    default: 'default'
  app_name:
    description: 'Application name'
    required: true
  kube_config:
    description: 'Kubeconfig content'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install etcdctl
      shell: bash
      run: |
        ETCD_VERSION="v3.5.5"
        curl -L https://github.com/etcd-io/etcd/releases/download/${ETCD_VERSION}/etcd-${ETCD_VERSION}-linux-amd64.tar.gz -o etcd.tar.gz
        tar xzvf etcd.tar.gz > /dev/null
        sudo mv etcd-${ETCD_VERSION}-linux-amd64/etcdctl /usr/local/bin/
        rm -rf etcd.tar.gz etcd-${ETCD_VERSION}-linux-amd64
        etcdctl version > /dev/null  # Hide output

    - name: Fetch ETCD Config
      id: fetch
      shell: bash
      run: |
        # Retrieve key-value pairs from ETCD securely
        OUTPUT=$(ETCDCTL_API=3 etcdctl \
          --endpoints="${{ inputs.etcd_host }}" \
          --user "${{ inputs.etcd_user }}:${{ inputs.etcd_password }}" \
          get "${{ inputs.etcd_key }}" --print-value-only 2>/dev/null)

        # Hide values from GitHub logs
        echo "::add-mask::$OUTPUT"

        # Store secret values without printing
        echo "config_values<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: "v1.32.0"

    - name: Configure kubectl
      shell: bash
      run: |
        mkdir -p ~/.kube
        echo "${{ inputs.kube_config }}" > ~/.kube/config

    - name: Create Kubernetes Secret
      shell: bash
      run: |
        # Read fetched config values directly from output
        CONFIG_VALUES="${{ steps.fetch.outputs.config_values }}"

        # Ensure values are hidden from logs
        echo "::add-mask::$CONFIG_VALUES"

        # Prepare key-value pairs for Secret (Base64 encode)
        SECRET_DATA=""
        while IFS='=' read -r key value; do
          key=$(echo -n "$key" | xargs)  # Trim whitespace
          value=$(echo -n "$value" | base64 -w0)  # Base64 encode value
          if [[ ! -z "$key" && ! -z "$value" ]]; then
            SECRET_DATA+="  $key: $value\n"
          fi
        done <<< "$CONFIG_VALUES"

        # Ensure no output is printed
        exec 1>/dev/null

        # Create Secret YAML securely
        cat <<EOF > secret.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${{ inputs.app_name }}-secret
          namespace: ${{ inputs.namespace }}
        type: Opaque
        data:
        $SECRET_DATA
        EOF

        # Apply Secret silently
        kubectl apply -f secret.yaml > /dev/null 2>&1
