name: "Set envs from loaded inputs"
description: "Parses loaded inputs into github envs."
inputs:
  inputs_data:
    description: 'Inputs data'
    required: true
runs:
  using: "composite"
  steps:
  - name: Parse and Set Environment Variables
    run: |
      echo "Parsing environment variables..."
      echo '${{ inputs.inputs_data }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV    
    shell: bash

