name: "Set envs from loaded inputs"
description: "Parses loaded inputs into github envs."
inputs:
  inputs_data:
    description: 'Inputs data in JSON format'
    required: true
runs:
  using: "composite"
  steps:
  - name: Parse and Set Environment Variables
    run: |
      echo "Parsing environment variables..."
      # Parse JSON and set each key-value pair as an environment variable
      echo "${{ inputs.inputs_data }}" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read -r line; do
        key=$(echo "$line" | cut -d'=' -f1)
        value=$(echo "$line" | cut -d'=' -f2-)
        # Remove quotes if present
        value=$(echo "$value" | sed 's/^"//;s/"$//')
        echo "$key=$value" >> $GITHUB_ENV
        echo "Set $key"
      done
    shell: bash

