name: Build & deploy 

on:
  workflow_call:

env:
  rollout_timeout: 300       
  version_file: ./package.json  
  inputs_files: ./k8s/cicd-inputs.yaml
  dockerhub_project: dataprocessor
  
permissions:
  contents: write

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: HerodotusDev/cicd/.github/actions/guard-branch@feat/env_standards
  define-matrix:
    runs-on: hero-arc-runners
    needs: [guard]
    outputs:
      matrix_apps: ${{ steps.define-matrix.outputs.matrix_apps }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load App Names
        id: load-app-names
        uses: HerodotusDev/cicd/.github/actions/load-inputs@feat/env_standards
        with:
          inputs_file: ${{env.inputs_files}}

      - name: Define apps matrix
        id: define-matrix
        run: |
          echo 'matrix_apps=${{ env.app_names }}' >> "$GITHUB_OUTPUT"

  siren:
    needs: [guard]
    runs-on: hero-arc-runners
    if: false
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.ARC_DOCKER_USERNAME }}
          password: ${{ env.ARC_DOCKER_PASSWORD }}

      - name: Pull Siren Image from Registry
        run: docker pull ${{ inputs.siren_image }}

      - name: Run Siren Check
        run: |
          docker run --rm ${{ inputs.siren_image }} || exit 1
        shell: bash

  version:
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: hero-arc-runners
    needs: [guard]
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Inputs from YAML
        id: load-inputs
        uses: HerodotusDev/cicd/.github/actions/load-inputs@feat/env_standards
        with:
          inputs_file: ${{env.inputs_files}}

      - name: Extract Version
        uses: HerodotusDev/cicd/.github/actions/extract-version@feat/env_standards
        id: version
        with:
          file: ${{ env.version_file }}

  build-and-push-image:
    needs: [define-matrix, version, guard]
    runs-on: hero-arc-runners
    strategy:
      matrix:
        app: ${{ fromJson(needs.define-matrix.outputs.matrix_apps) }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Inputs from YAML
        id: load-inputs
        uses: HerodotusDev/cicd/.github/actions/load-inputs@feat/env_standards
        with:
          inputs_file: ${{env.inputs_files}}

      - name: Build and push image
        uses: HerodotusDev/cicd/.github/actions/build-and-push-image@feat/env_standards
        env:
          overwrite_dockerfile: storage-proofs
          dockerfile: ${{ env.REPO_NAME == 'backend' && 'overwrite_dockerfile' || matrix.app }}          
        with:
          dockerhub_project: ${{ env.dockerhub_project }}
          app_name: ${{ matrix.app }}
          version: ${{ needs.version.outputs.version }}
          docker_username: ${{ env.ARC_DOCKER_USERNAME }}
          docker_password: ${{ env.ARC_DOCKER_PASSWORD }}
          dockerfile: ./docker/Dockerfile.${{ matrix.app }}

  create-git-tag:
    needs: [version, build-and-push-image, guard]
    runs-on: hero-arc-runners 
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Inputs from YAML
        id: load-inputs
        uses: HerodotusDev/cicd/.github/actions/load-inputs@feat/env_standards
        with:
          inputs_file: ${{env.inputs_files}}

      - name: Create Git tag
        uses: HerodotusDev/cicd/.github/actions/create-git-tag@feat/env_standards
        with:
          tag: ${{ needs.version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [define-matrix, version, create-git-tag, build-and-push-image, guard]
    runs-on: hero-arc-runners
    strategy:
      matrix:
        app: ${{ fromJson(needs.define-matrix.outputs.matrix_apps) }}
    if: always()
    outputs:
      secret_changed: ${{ steps.pull_config.outputs.secret_changed }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Inputs from YAML
        id: load-inputs
        uses: HerodotusDev/cicd/.github/actions/load-inputs@feat/env_standards
        with:
          inputs_file: ${{env.inputs_files}}
      - name: Pull  config from etcd
        id: pull_config
        uses: HerodotusDev/cicd/.github/actions/pull-etcd-config@feat/env_standards
        env:
          overwrite_app_name: storage-proofs
          app_name: ${{ env.REPO_NAME == 'backend' && 'overwrite_app_name' || matrix.app }}        
        with:
          namespace: ${{ env.namespace }}
          app_name: ${{ env.app_name }}
          etcd_user: ${{ env.ARC_ETCD_USER }}
          etcd_password: ${{ env.ARC_ETCD_PASSWORD }}          
          etcd_root: ${{ env.repo_name }}

      - name: Deploy to Kubernetes
        uses: HerodotusDev/cicd/.github/actions/deploy-to-k8s@feat/env_standards
        with:
          namespace: ${{ env.namespace }}
          deployment_file: ./k8s/${{ env.k8s_env }}/${{ matrix.app }}-deployment.yaml
          ingress_file: ./k8s/${{ env.k8s_env }}/${{ matrix.app }}-ingress.yaml
          rollout_timeout: ${{ env.rollout_timeout }}
          image_tag: ${{ needs.version.outputs.version }}
          dockerhub_project: ${{ env.dockerhub_project }}
          app_name: ${{ matrix.app }}
          secret_changed: ${{ steps.pull_config.outputs.secret_changed }}