name: Checkov Security Scan

on:
    workflow_dispatch:
    pull_request:
        branches: [main] # Trigger when PR targets these branches



permissions:
    contents: read
    
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: github_actions
