name: Build & deploy 

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      app_name:
        required: true
        type: string
      dockerhub_project:
        required: true
        type: string
      deployment_file:
        required: true
        type: string
      ingress_file:
        required: true
      rollout_timeout:
        required: true
      version: 
        required: true
    secrets:
      KUBE_CONFIG:
        required: true


permissions:
  contents: write

jobs:
  deploy-staging:
    needs: [version, create-git-tag, build-and-push-image]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes
        uses: ./.github/actions/deploy-to-k8s
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}
          namespace: ${{ inputs.app_name }}
          deployment_file: ${{ inputs.deployment_file }}
          ingress_file: ${{ inputs.ingress_file }}
          rollout_timeout: ${{ inputs.rollout_timeout }}
          image_tag: ${{ inputs.version }}
          dockerhub_project: ${{ inputs.dockerhub_project }}
          app_name: ${{ inputs.app_name }}
