name: Deploy version

on:
  workflow_call:
    inputs:
      version:
        description: "Enter version to be deployed"
        required: true
        type: string
      inputs_file:
        type: string
        default: ./k8s/cicd-inputs.yaml  
    secrets:
      KUBE_CONFIG:
        required: true
      ETCD_USER:
        required: false
      ETCD_PASSWORD:
        required: false        

env:
  deployment_file: ./k8s/deployment.yaml
  ingress_file: ./k8s/ingress.yaml
  rollout_timeout: 300 

permissions:
  contents: write

jobs:

  load-inputs:
    runs-on: ubuntu-latest
    outputs:
      env_vars: ${{ steps.load-inputs.outputs.env_vars }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # ✅ Pull the repository that triggered the workflow
          ref: ${{ github.ref }}  # ✅ Check out the same branch as the trigger
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use GitHub token for access
        
      - name: Load Inputs from YAML
        id: load-inputs
        uses: HerodotusDev/cicd/.github/actions/load-inputs@main
        with:
          inputs_file: ${{ inputs.inputs_file }}

  deploy-staging:
    needs: load-inputs
    runs-on: ubuntu-latest
    if: always()
    steps:

      - name: Set inputs
        uses: HerodotusDev/cicd/.github/actions/set-inputs@main
        with:
          inputs_data: ${{ needs.load-inputs.outputs.env_vars }}

      - name: Checkout Caller Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}  # ✅ Pull the repository that triggered the workflow
          ref: ${{ github.ref }}  # ✅ Check out the same branch as the trigger
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use GitHub token for access

      - name: Pull config from etcd
        uses: HerodotusDev/cicd/.github/actions/pull-etcd-config@main
        if: ${{ env.pull_etcd_config == 'true' }}
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}
          namespace: ${{ env.namespace }}
          app_name: ${{ env.app_name }}
          etcd_user: ${{ secrets.ETCD_USER }}
          etcd_password: ${{ secrets.ETCD_PASSWORD }}
          etcd_key: ${{ env.etcd_key}}
  

      - name: Deploy to Kubernetes
        uses: HerodotusDev/cicd/.github/actions/deploy-to-k8s@main
        with:
          kube_config: ${{ secrets.KUBE_CONFIG }}
          namespace: ${{ env.namespace }}
          deployment_file: ${{ env.deployment_file }}
          ingress_file: ${{ env.ingress_file }}
          rollout_timeout: ${{ env.rollout_timeout }}
          image_tag: ${{ inputs.version }}
          dockerhub_project: ${{ env.dockerhub_project }}
          app_name: ${{ env.app_name }}
